// Generated by delombok at Sun Dec 01 13:28:22 MSK 2013
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package spaceisnear.game.messages;

import lombok.Getter;

public class MessageTimePassed extends BroadcastMessage {

    @Getter private final int timePassed;

    public MessageTimePassed(int time) {
	super(MessageType.TIME_PASSED);
	this.timePassed = time;
    }
}
