// Generated by delombok at Sun Dec 01 13:28:22 MSK 2013
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package spaceisnear.game.bundles;

/**
 * @author white_oak
 */
public abstract class Bundle {
	
	public byte[] bytes;
	
	
	public byte[] getBytes() {
		return this.bytes;
	}
}