// Generated by delombok at Sun Dec 01 13:28:22 MSK 2013
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package spaceisnear.game.components.inventory;

import spaceisnear.game.objects.items.Size;
import spaceisnear.game.objects.items.StaticItem;

/**
 * @author White Oak
 */
public class InventorySlot {

    private int item;
    private Size size;
    private String name;

    public InventorySlot(Size size, String name) {
	this.size = size;
	this.name = name;
    }

    @Deprecated
    InventorySlot() {

    }

    public int getItem() {
	return this.item;
    }

    public void setItem(final int item) {
	this.item = item;
    }

    public Size getSize() {
	return this.size;
    }

    public String getName() {
	return this.name;
    }
}
