// Generated by delombok at Sun Dec 01 13:28:22 MSK 2013
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package spaceisnear.game.messages;

import spaceisnear.game.bundles.MessageBundle;

/**
 * Sent only by server as a result of Items' interactions.
 *
 * @author White Oak
 */
public class MessageCreated extends Message implements NetworkableMessage {

    private final String json;

    public MessageCreated(String json) {
	super(MessageType.CREATED);
	this.json = json;
    }

    @Override
    public MessageBundle getBundle() {
	MessageBundle messageBundle = new MessageBundle(getMessageType());
	messageBundle.bytes = json.getBytes();
	return messageBundle;
    }

    public static MessageCreated getInstance(byte[] b) {
	return new MessageCreated(new String(b));
    }

    public String getJson() {
	return this.json;
    }
}
