// Generated by delombok at Sun Dec 01 13:28:22 MSK 2013
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package spaceisnear.game.messages;

import spaceisnear.game.bundles.MessageBundle;

public class MessageMapSent extends Message implements NetworkableMessage {

    private final String map;

    public MessageMapSent(String map) {
	super(MessageType.MAP_SENT);
	this.map = map;
    }

    @Override
    public MessageBundle getBundle() {
	MessageBundle messageBundle = new MessageBundle(getMessageType());
	messageBundle.bytes = map.getBytes();
	return messageBundle;
    }

    public static MessageMapSent getInstance(byte[] b) {
	return new MessageMapSent(new String(b));
    }

    public String getMap() {
	return this.map;
    }
}
