// Generated by delombok at Sun Dec 01 13:28:22 MSK 2013
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spaceisnear.game.messages;

import spaceisnear.Context;

public class MessageToSend extends DirectedMessage {

    private final NetworkableMessage message;

    public MessageToSend(NetworkableMessage m) {
	super(MessageType.NETWORKING, Context.NETWORKING_ID);
	message = m;
    }

    public NetworkableMessage getMessage() {
	return this.message;
    }
}
