// Generated by delombok at Sun Dec 01 13:28:22 MSK 2013
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package spaceisnear.game.messages;

public class MessageTimePassed extends Message {
	private int timePassed;
	
	public MessageTimePassed(int time) {
		super(MessageType.TIME_PASSED);
		this.timePassed = time;
	}
	
	
	public int getTimePassed() {
		return this.timePassed;
	}
}