// Generated by delombok at Sun Dec 01 13:28:22 MSK 2013
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package spaceisnear.game.messages;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import spaceisnear.Utils;
import spaceisnear.game.bundles.MessageBundle;

/**
 * @author LPzhelud
 */
@RequiredArgsConstructor public abstract class Message {

    @Getter private final MessageType messageType;

    public MessageBundle getBundle() {
	return new MessageBundle(Utils.GSON.toJson(this).getBytes(), getMessageType());
    }
}
