// Generated by delombok at Sun Dec 01 13:28:22 MSK 2013
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spaceisnear.game.messages;

import lombok.Getter;
import spaceisnear.abstracts.Context;

public class MessageToSend extends DirectedMessage {

    @Getter private final NetworkableMessage message;
    @Getter private final boolean broadcast;

    public MessageToSend(NetworkableMessage m, boolean broadcast) {
	super(MessageType.NETWORKING, Context.NETWORKING_ID);
	message = m;
	this.broadcast = broadcast;
    }

    public MessageToSend(NetworkableMessage m) {
	this(m, true);
    }
}
