// Generated by delombok at Sun Dec 01 13:28:22 MSK 2013
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package spaceisnear.game.messages;

import spaceisnear.game.bundles.MessageBundle;

/**
 * @author LPzhelud
 */
public abstract class Message {

    private final MessageType messageType;

    public MessageBundle getBundle() {
	return new MessageBundle(getMessageType());
    }

    @java.beans.ConstructorProperties({"messageType"})
    public Message(final MessageType messageType) {

	this.messageType = messageType;
    }

    public MessageType getMessageType() {
	return this.messageType;
    }
}
