// Generated by delombok at Sun Dec 01 13:28:22 MSK 2013
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package spaceisnear.game.messages;

import spaceisnear.Utils;
import spaceisnear.game.bundles.MessageBundle;

/**
 * @author LPzhelud
 */
public class MessageControlled extends DirectedMessage implements NetworkableMessage {

    private final Type type;

    public MessageControlled(Type type, int id) {
	super(MessageType.CONTROLLED, id);
	this.type = type;
    }

    public enum Type {

	UP,
	DOWN,
	LEFT,
	RIGHT;

    }

    @Override
    public MessageBundle getBundle() {
	MessageBundle messageBundle = new MessageBundle(MessageType.CONTROLLED);
	messageBundle.bytes = Utils.GSON.toJson(this).getBytes();
	return messageBundle;
    }

    public static MessageControlled getInstance(byte[] b) {
	return Utils.GSON.fromJson(new String(b), MessageControlled.class);
    }

    public Type getType() {
	return this.type;
    }
}
