type = getMessageType {}
    if (type == TIME_PASSED){
	ticksSinceOpened = getProperty {"ticksSinceOpened"}
	if(ticksSinceOpened == null){
	    ticksSinceOpened = 0;
	}
	ticksSinceOpened = ticksSinceOpened + 1
	setProperty {"ticksSinceOpened", ticksSinceOpened}
	if (ticksSinceOpened > 100){
	    setFullyPathable {false}
	    setProperty {opened, false}
	    sendAnimationQueueToRequestor {"3, 2, 1, 0", 200}
	    unregisterForTimeMessages {}
	}
    }