if (type == PROPERTY_SET){
	name = getPropertyMessageName {}
	if (name == messages){
	    //Tell method that we are fine with handling the message by ourself
	    dontProcessOnYourOwn {}
	    //Add to property
	    value = getPropertyMessageValue {}
	    concatenateProperty {"messages", LINE_SEPARATOR}
	    concatenateProperty {"messages", value}
	    //Send to player the message
	    sendPlayerPrivateMessage{value}
	}
}