package spaceisnear.game.components;

/**
 *
 * @author White Oak
 */
public enum ComponentType {

    BREATHING, GAMER_PLAYER_POSITION, HEALTH, INTELLIGENCE, PAINTABLE,
    NAME, NETWORKING, PLAYER, PLAYER_CONTROLLABLE, POSITION,
    UI, ITEM_PAINTABLE, INVENTORY, ITEM_PROPERTIES, VARIABLES,
    PULLABLE, INVENTORY_PAINTABLE, LIGHT, SHADOW, PLAYER_CHUNK_OBSERVER,
    PATIENT_CLIENT
}
