// Generated by delombok at Sun Dec 01 13:28:22 MSK 2013
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package spaceisnear.game.messages.service;

import spaceisnear.game.messages.Message;
import spaceisnear.game.messages.MessageType;

/**
 * @author LPzhelud
 */
public class MessageNetworkState extends Message {
	private int state;
	
//0 - n a
//1 - connected
//2 - disconnected
//3 - idle
	public MessageNetworkState(int state) {
		super(MessageType.NETWORK_STATE);
		this.state = state;
	}
	
	
	public int getState() {
		return this.state;
	}
}