// Generated by delombok at Sun Dec 01 13:28:22 MSK 2013
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package spaceisnear.game.ui;

import java.io.Serializable;

import lombok.*;

/**
 * @author white_oak
 */
@NoArgsConstructor(access = AccessLevel.PRIVATE)
@AllArgsConstructor
public class Position implements Serializable {

	@Getter
	@Setter
	private int x, y;

	public boolean equals(int x, int y) {
		return x == this.x && y == this.y;
	}

	@Override
	public String toString() {
		return new StringBuilder().append('(').append(x).append(", ").append(y).append(')').toString();
	}

	public int distanceTo(Position p) {
		int dx = Math.abs(p.x - x);
		int dy = Math.abs(p.y - y);
		return dx + dy;
	}

	public Position getNewWithDelta(Position p) {
		return getNewWithDelta(p.x, p.y);
	}

	public Position getNewWithDelta(int x, int y) {
		return new Position(x + this.x, y + this.y);
	}
}
