// Generated by delombok at Sun Dec 01 13:28:22 MSK 2013
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package spaceisnear.game.components;

import lombok.AllArgsConstructor;

/**
 * @author LPzhelud
 */
@AllArgsConstructor public class ComponentState {

    private String name;
    private Object value;

    public String getName() {
	return this.name;
    }

    public void setName(final String name) {
	this.name = name;
    }

    public Object getValue() {
	return this.value;
    }

    public void setValue(final Object value) {
	this.value = value;
    }
}
