// Generated by delombok at Sun Dec 01 13:28:22 MSK 2013
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package spaceisnear.game.components;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import spaceisnear.game.messages.Message;
import spaceisnear.Context;
import spaceisnear.game.GameContext;
import spaceisnear.game.objects.GameObject;
import spaceisnear.game.objects.Position;

/**
 * @author LPzhelud
 */
public abstract class Component {

    private final HashMap<String, ComponentState> states = new HashMap<>();
    private Context context = null;
    private final ComponentType type;
    private int ownerId = -1;

    public Component(ComponentType type) {
	this.type = type;
    }

    public abstract void processMessage(Message message);

    public void setContext(Context context) {
	if (this.context == null) {
	    this.context = context;
	}
    }

    public static Component getInstance(ComponentStateBundle[] states, Class component, Context c) throws ClassNotFoundException,
	    NoSuchMethodException, InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException {
	try {
	    final Constructor constructor = component.getDeclaredConstructor();
	    constructor.setAccessible(true);
	    Component newInstance = (Component) constructor.newInstance();
	    for (ComponentStateBundle state : states) {
		ComponentState componentState = state.getState();
		newInstance.states.put(componentState.getName(), componentState);
	    }
	    newInstance.setContext(c);
	    return newInstance;
	} catch (InstantiationException | IllegalAccessException ex) {
	    Logger.getLogger(Component.class.getName()).log(Level.SEVERE, null, ex);
	}
	return null;
    }

    protected ComponentState getStateNamed(String name) {
	return states.get(name);
    }

    protected Object getStateValueNamed(String name) {
	return getStateNamed(name).getValue();
    }

    protected GameObject getOwner() {
	if (getOwnerId() == -1) {
	    throw new RuntimeException("Owner id is -1");
	}
	return ((GameContext) getContext()).getObjects().get(getOwnerId());
    }

    public int getOwnerId() {
//	return (Integer) getStateValueNamed("owner");
	return ownerId;
    }

    public final void setOwnerId(int id) {
//	states.put("owner", new ComponentState("owner", id));
	ownerId = id;
    }

    protected void addState(ComponentState state) {
	states.put(state.getName(), state);
    }

    public HashMap<String, ComponentState> getStates() {
	return this.states;
    }

    protected Context getContext() {
	return this.context;
    }

    protected Position getPosition() {
	GameObject owner = getOwner();
	for (Component component : owner.getComponents()) {
	    switch (component.getType()) {
		case POSITION:
		case GAMER_PLAYER_POSITION:
		    PositionComponent positionComponent = (PositionComponent) component;
		    return positionComponent.getPosition();
		default:
		    throw new RuntimeException("No position component here.");
	    }
	}
	return null;
    }

    public ComponentType getType() {
	return type;
    }

}
