// Generated by delombok at Sun Dec 01 13:28:22 MSK 2013
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package spaceisnear.game.bundles;

public class JSONBundle extends Bundle {
	private String body;
	
	public JSONBundle() {
		
	}
	
	@Override
	public byte[] getBytes() {
		return body.getBytes();
	}
	
	@java.beans.ConstructorProperties({"body"})
	
	public JSONBundle(final String body) {
		
		this.body = body;
	}
	
	
	public String getBody() {
		return this.body;
	}
}