// Generated by delombok at Sun Dec 01 13:28:22 MSK 2013
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package spaceisnear.game.bundles;

import spaceisnear.game.messages.MessageType;

/**
 * @author white_oak
 */
public class MessageBundle extends Bundle {

    public MessageType messageType;

    private MessageBundle() {
    }

    public MessageBundle(byte[] b, final MessageType messageType) {
	bytes = b;
	this.messageType = messageType;
    }

    @java.beans.ConstructorProperties({"messageType"})
    public MessageBundle(final MessageType messageType) {
	this.messageType = messageType;
    }
}
