// Generated by delombok at Sun Dec 01 13:28:22 MSK 2013
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package spaceisnear.server;

import java.io.IOException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import lombok.Getter;
import org.newdawn.slick.SlickException;
import spaceisnear.AbstractGameObject;
import spaceisnear.game.GameContext;
import spaceisnear.game.components.server.HealthComponent;
import spaceisnear.game.layer.AtmosphericLayer;
import spaceisnear.game.layer.ObstaclesLayer;
import spaceisnear.game.messages.HurtMessage;
import spaceisnear.game.messages.MessageLog;
import spaceisnear.game.messages.MessageTimePassed;
import spaceisnear.game.messages.service.MessagePaused;
import spaceisnear.game.messages.service.MessageUnpaused;
import spaceisnear.game.objects.Position;
import spaceisnear.game.objects.items.ItemsReader;
import spaceisnear.game.ui.console.LogLevel;
import spaceisnear.game.ui.console.LogString;
import spaceisnear.server.objects.Player;
import spaceisnear.server.objects.items.ItemAdder;
import spaceisnear.server.objects.items.ServerItemsArchive;

/**
 * @author white_oak
 */
public class ServerCore implements Runnable {

    @Getter private final ServerContext context;
    private final boolean unbreakable = true;
    private boolean paused = false;
    private static final int QUANT_TIME = 20;
    @Getter private boolean alreadyPaused;
    private long timePassed;
    private AtmosphereThread at = new AtmosphereThread();

    public ServerCore() throws IOException {
	int width = GameContext.MAP_WIDTH;
	int height = width;
	final ArrayList<AbstractGameObject> objects = new ArrayList<>();
	try {
	    ServerItemsArchive.itemsArchive = new ServerItemsArchive(ItemsReader.read());
	} catch (SlickException ex) {
	    Logger.getLogger(ServerCore.class.getName()).log(Level.SEVERE, null, ex);
	} catch (Exception ex) {
	    Logger.getLogger(ServerCore.class.getName()).log(Level.SEVERE, null, ex);
	}
	ObstaclesLayer obstacles = new ObstaclesLayer(width, height);
	AtmosphericLayer atmosphere = new AtmosphericLayer(width, height);
	context = new ServerContext(new ServerNetworking(this), objects, obstacles, atmosphere);
	//items adding
	ItemAdder itemAdder = new ItemAdder(context);
	itemAdder.addItems();
    }

    @Override
    public void run() {
	at.start();
	while (unbreakable) {
	    //networking
	    context.getNetworking().processReceivedQueue();
	    //game
	    if (!paused) {
		MessageTimePassed messageTimePassed = new MessageTimePassed(QUANT_TIME);
		context.sendThemAll(messageTimePassed);
		for (AbstractGameObject gameObject : getContext().getObjects()) {
		    if (gameObject != null) {
			gameObject.process();
		    }
		}
	    } else {
		if (!alreadyPaused) {
		    alreadyPaused = true;
		}
	    }
	    try {
		Thread.sleep(QUANT_TIME);
	    } catch (InterruptedException ex) {
		Logger.getLogger(ServerCore.class.getName()).log(Level.SEVERE, null, ex);
	    }
	    sendPressure();
	}
    }

    private void sendPressure() {
	timePassed += QUANT_TIME;
	if (timePassed > 4000 && !context.getPlayers().isEmpty()) {
	    Player get = context.getPlayers().get(0);
	    final int pressure = context.getAtmosphere().getPressure(get.getPosition().getX(), get.getPosition().getY());
	    context.getNetworking().sendToAll(new MessageLog(new LogString("Pressure: " + pressure, LogLevel.DEBUG)));
	    timePassed = 0;
	}
    }

    private void checkHealthStatuses() {
	for (Player player : getContext().getPlayers()) {
	    Position position = player.getPosition();
	    int pressure = context.getAtmosphere().getPressure(position.getX(), position.getY());
	    if (pressure < AtmosphericLayer.PRESSURE_HARD_TO_BREATH) {
		HurtMessage hurtMessage;
		if (pressure < AtmosphericLayer.PRESSURE_ENOUGH_TO_BREATH) {
		    hurtMessage = new HurtMessage(HealthComponent.SUFFOCATING_DAMAGE, HurtMessage.Type.SUFFOCATING,
			    player.getId());
		} else {
		    hurtMessage = new HurtMessage(HealthComponent.LIGHT_SUFFOCATING_DAMAGE, HurtMessage.Type.SUFFOCATING,
			    player.getId());
		}
		getContext().sendDirectedMessage(hurtMessage);
	    }
	}
    }

    public void pause() {
	paused = true;
	context.getNetworking().sendToAll(new MessagePaused());
	System.out.println("Server\'s been paused");
    }

    public void unpause() {
	context.getNetworking().sendToAll(new MessageUnpaused());
	paused = false;
	alreadyPaused = false;
    }

    public void host() throws IOException {
	getContext().getNetworking().host();
    }

    public Player addPlayer(int connectionID) {
	return context.addPlayer(connectionID);
    }

    private class AtmosphereThread extends Thread {

	@Override
	public void run() {
	    while (unbreakable) {
		if (!paused) {
		    context.getAtmosphere().tickAtmosphere(context);
		    checkHealthStatuses();
		}
		try {
		    Thread.sleep(ATMOSPHERE_DELAY);
		} catch (InterruptedException ex) {
		    Logger.getLogger(ServerCore.class.getName()).log(Level.SEVERE, null, ex);
		}
	    }
	}
	public static final long ATMOSPHERE_DELAY = 2000L;

    }
}
