// Generated by delombok at Sun Dec 01 13:28:22 MSK 2013
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package spaceisnear.game.layer;

import lombok.Data;
import lombok.Getter;
import lombok.NonNull;
import lombok.Setter;

/**
 * @author LPzhelud
 */
@Data public abstract class Layer {

    private int width;
    private int height;
    private int x;
    private int y;

    public Layer(int width, int height) {
	this.width = width;
	this.height = height;
    }

}
