// Generated by delombok at Sun Dec 01 13:28:22 MSK 2013
package spaceisnear.server.objects;

import spaceisnear.game.components.BreathingComponent;
import spaceisnear.game.components.HealthComponent;
import spaceisnear.game.components.NameComponent;
import spaceisnear.game.components.PlayerComponent;
import spaceisnear.game.components.PositionComponent;
import spaceisnear.game.components.inventory.InventoryComponent;
import spaceisnear.game.objects.GameObjectType;
import spaceisnear.server.GameContext;

/**
 * @author LPzhelud
 */
public class Player extends GameObject {

    public int connectionID;
    private final HealthComponent healthComponent;

    public Player(GameContext context, int connectionID) {
	super(GameObjectType.PLAYER, null);
	PositionComponent pc = new PositionComponent(24, 18, getId());
	pc.setContext(context);
	healthComponent = new HealthComponent(getId());
	addComponents(pc, new PlayerComponent(getId()), healthComponent, new BreathingComponent(getId()),
		new InventoryComponent(getId()), new NameComponent(null, getId()));
	this.connectionID = connectionID;
    }

    public String getNickname() {
	return ((NameComponent) getComponents().getLast()).getNickname();
    }

    public void setNickname(String nickname) {
	((NameComponent) getComponents().getLast()).setNickname(nickname);
    }

    public HealthComponent getHealthComponent() {
	return this.healthComponent;
    }
}
