// Generated by delombok at Sun Dec 01 13:28:22 MSK 2013
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package spaceisnear.game.objects;

import java.util.*;
import java.util.concurrent.ConcurrentLinkedQueue;
import lombok.Getter;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;
import lombok.Setter;
import spaceisnear.AbstractGameObject;
import spaceisnear.game.GameContext;
import spaceisnear.game.bundles.ObjectBundle;
import spaceisnear.game.components.Component;
import spaceisnear.game.components.ComponentState;
import spaceisnear.game.components.ComponentStateBundle;
import spaceisnear.game.messages.Message;

/**
 * @author LPzhelud
 */
@RequiredArgsConstructor public abstract class ClientGameObject extends AbstractGameObject {

    private final ConcurrentLinkedQueue<Message> messages = new ConcurrentLinkedQueue<>();
    @Getter private int id = -1;
    @Getter @Setter private boolean destroyed = false;
    @Getter private List<Component> components = new LinkedList<>();
    @NonNull @Getter private final GameObjectType type;
    @NonNull @Getter @Setter private GameContext context;

    public void setId(int id) {
	if (this.id == -1) {
	    this.id = id;
	    for (Component component : components) {
		component.setOwnerId(id);
	    }
	}
    }

    public final synchronized void addComponents(Component... a) {
	for (Component component : a) {
	    component.setContext(context);
	}
	this.components.addAll(Arrays.asList(a));
    }

    @Override
    public final void message(Message message) {
	messages.add(message);
    }

    private synchronized GameObjectState getState() {
	ComponentStateBundle[][] states = new ComponentStateBundle[components.size()][];
	String[] classes = new String[components.size()];
	for (int i = 0; i < classes.length; i++) {
	    classes[i] = components.get(i).getClass().getName();
	    HashMap<String, ComponentState> states1 = components.get(i).getStates();
	    ComponentStateBundle[] bundles = new ComponentStateBundle[states1.size()];
	    Collection<ComponentState> values = states1.values();
	    int j = 0;
	    for (ComponentState componentState : values) {
		bundles[j] = new ComponentStateBundle(componentState);
		j++;
	    }
	    states[i] = bundles;
	}
	return new GameObjectState(states, classes);
    }

    @Override
    public final synchronized ObjectBundle getBundle() {
	return new ObjectBundle(getState(), id, type);
    }

    @Override
    public synchronized void process() {
	if (destroyed) {
	    return;
	}
	while (messages.size() > 0) {
	    Message message = messages.poll();
	    for (Component component : components) {
		component.processMessage(message);
	    }
	}
    }

    protected void setComponents(List<Component> components) {
	this.components = components;
    }
}
