// Generated by delombok at Sun Dec 01 13:28:22 MSK 2013
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package spaceisnear.game.objects;

import java.util.*;
import java.util.concurrent.ConcurrentLinkedQueue;
import lombok.*;
import spaceisnear.abstracts.AbstractGameObject;
import spaceisnear.game.GameContext;
import spaceisnear.game.components.Component;
import spaceisnear.game.components.client.PaintableComponent;
import spaceisnear.game.messages.Message;

/**
 * @author LPzhelud
 */
@RequiredArgsConstructor public abstract class ClientGameObject extends AbstractGameObject {

    @Setter @Getter private ConcurrentLinkedQueue<Message> messages = new ConcurrentLinkedQueue<>();
    @Getter private int id = -1;
    @Getter @Setter private boolean destroyed = false;
    @Getter private List<Component> components = new ArrayList<>();
    @NonNull @Getter private final GameObjectType type;
    @Getter private GameContext context;

    public void setId(int id) {
	if (this.id == -1) {
	    this.id = id;
	    for (Component component : components) {
		component.setOwnerId(id);
	    }
	}
    }

    public final synchronized void addComponents(Component... a) {
	for (Component component : a) {
	    component.setContext(context);
	}
	this.components.addAll(Arrays.asList(a));
    }

    @Override
    public final void message(Message message) {
	messages.add(message);
    }

    @Override
    public synchronized void process() {
	if (destroyed) {
	    return;
	}
	while (messages.size() > 0) {
	    Message message = messages.poll();
	    for (int i = 0; i < components.size(); i++) {
		Component component = components.get(i);
		component.processMessage(message);
	    }
	}
    }

    public void setContext(GameContext context) {
	this.context = context;
	for (Component component : components) {
	    component.setContext(context);
	    if (component instanceof PaintableComponent) {
		context.addPaintable((PaintableComponent) component);
	    }
	}
    }

    protected void setComponents(List<Component> components) {
	this.components = components;
    }

    public boolean isAnimated() {
	boolean result = false;
	for (int i = 0; i < components.size(); i++) {
	    Component component = components.get(i);
	    result |= component.hasAnimation();
	}
	return result;
    }
}
