// Generated by delombok at Sun Dec 01 13:28:22 MSK 2013
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package spaceisnear.game.objects;

import java.util.logging.Level;
import java.util.logging.Logger;
import spaceisnear.game.components.Component;
import spaceisnear.game.components.ComponentState;
import spaceisnear.game.components.ComponentStateBundle;

/**
 * @author LPzhelud
 */
public class GameObjectState {
	private ComponentStateBundle[][] states;
	private String[] classes;
	
	GameObjectState() {
		
	}
	
	public Component[] getComponents() {
		Component[] components = new Component[classes.length];
		for (int i = 0; i < classes.length; i++) {
			try {
				Class class1 = Class.forName(classes[i]);
				components[i] = Component.getInstance(states[i], class1);
			} catch (ClassNotFoundException ex) {
				Logger.getLogger(GameObjectState.class.getName()).log(Level.SEVERE, null, ex);
			}
		}
		return components;
	}
	
	@java.beans.ConstructorProperties({"states", "classes"})
	
	public GameObjectState(final ComponentStateBundle[][] states, final String[] classes) {
		
		this.states = states;
		this.classes = classes;
	}
}