// Generated by delombok at Sun Dec 01 13:28:22 MSK 2013
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package spaceisnear.game.objects;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

/**
 * @author white_oak
 */
@AllArgsConstructor public class Position {

    @Getter @Setter private int x, y;

    Position() {
    }

    public boolean equals(int x, int y) {
	return x == this.x && y == this.y;
    }

}
