// Generated by delombok at Sun Dec 01 13:28:22 MSK 2013
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package spaceisnear.game.objects;

/**
 * @author white_oak
 */
public class Position {
	private int x;
	private int y;
	
	Position() {
		
	}
	
	@java.beans.ConstructorProperties({"x", "y"})
	
	public Position(final int x, final int y) {
		
		this.x = x;
		this.y = y;
	}
	
	
	public int getX() {
		return this.x;
	}
	
	
	public int getY() {
		return this.y;
	}
	
	
	public void setX(final int x) {
		this.x = x;
	}
	
	
	public void setY(final int y) {
		this.y = y;
	}
}