// Generated by delombok at Sun Dec 01 13:28:22 MSK 2013
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package spaceisnear.game.layer;

/**
 * @author LPzhelud
 */
public abstract class Layer {

    private int width;
    private int height;
    private int x;
    private int y;

    public Layer(int width, int height) {

	this.width = width;
	this.height = height;
    }

    public int getWidth() {
	return this.width;
    }

    public int getHeight() {
	return this.height;
    }

    protected void setWidth(final int width) {
	this.width = width;
    }

    protected void setHeight(final int height) {
	this.height = height;
    }

    public int getX() {
	return this.x;
    }

    public int getY() {
	return this.y;
    }

    public void setX(final int x) {
	this.x = x;
    }

    public void setY(final int y) {
	this.y = y;
    }
}
