// Generated by delombok at Sun Dec 01 13:28:22 MSK 2013
package spaceisnear.game.layer;

import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.g2d.SpriteBatch;
import com.badlogic.gdx.graphics.g2d.TextureRegion;
import spaceisnear.game.GameContext;

/**
 * @author LPzhelud
 */
public class TiledLayer extends Layer {

    private int[][] map;//[x][y]

//    private NullLayer obstaclesMap;
    private final TextureRegion[] tiles;
    private final int tileWidth;
    private final int tileHeight;
    private final int horizontalTilesNumber;
    private final int verticalTilesNumber;
    private int maxXTiles;
    private int maxYTiles;
    private int startx;
    private int starty;
    private int startx_absolute;
    private int starty_absolute;

    public void setStartx(int startx) {
	this.startx = startx < 0 ? 0 : startx >= horizontalTilesNumber ? horizontalTilesNumber - 1 : startx;
    }

    public void setStarty(int starty) {
	this.starty = starty < 0 ? 0 : starty >= verticalTilesNumber ? verticalTilesNumber - 1 : starty;
    }

    public void moveCameraTo(int x, int y) {
	startx_absolute = x;
	starty_absolute = y;
	setStartx(startx_absolute);
	setStarty(starty_absolute);
    }

    public void moveLeft() {
	startx_absolute--;
	setStartx(startx_absolute);
    }

    public void moveRight() {
	startx_absolute++;
	setStartx(startx_absolute);
    }

    public void moveUp() {
	starty_absolute--;
	setStarty(starty_absolute);
    }

    public void moveDown() {
	starty_absolute++;
	setStarty(starty_absolute);
    }

    public void setWindowWidth(int w) {
	maxXTiles = w / getTileWidth() + 2;
    }

    public void setWindowHeight(int h) {
	maxYTiles = h / getTileHeight() + 2;
    }

    public TiledLayer(Texture image, int tileWidth, int tileHeight, int width, int height) {
	super(width * tileWidth, height * tileHeight);
	if (image.getWidth() / tileWidth * tileWidth != image.getWidth() || image.getHeight() / tileHeight * tileHeight != image.getHeight()) {
	    throw new IllegalArgumentException();
	}
	this.tileHeight = tileHeight;
	this.tileWidth = tileWidth;
	tiles = chopImage(image);
	map = new int[width][height];
	horizontalTilesNumber = width;
	verticalTilesNumber = height;
    }

    //Updated on 1st January 2014
    private TextureRegion[] chopImage(Texture image) {
	int tilesX = image.getWidth() / GameContext.TILE_WIDTH;
	int tilesY = image.getHeight() / GameContext.TILE_HEIGHT;
	TextureRegion[] regions = new TextureRegion[tilesY * tilesX];
	for (int i = 0; i < tilesY; i++) {
	    for (int j = 0; j < tilesX; j++) {
		regions[i * tilesX + j] = new TextureRegion(image,
			j * GameContext.TILE_WIDTH, i * GameContext.TILE_HEIGHT,
			GameContext.TILE_WIDTH, GameContext.TILE_HEIGHT);
	    }
	}
	return regions;
    }

    public void setTile(int x, int y, int tileId) {
	map[x][y] = tileId;
    }

    public int getTile(int x, int y) {
	return map[x][y];
    }

    public void fillRectTile(int x, int y, int w, int h, int tileId) {
	for (int i = y; i < y + h; i++) {
	    for (int j = x; j < w + x; j++) {
		setTile(j, i, tileId);
	    }
	}
    }

    public void paintLayer(SpriteBatch batch) {
	int maxw = (startx + maxXTiles) > map.length ? map.length : startx + maxXTiles;
	int maxh = (starty + maxYTiles) > map[0].length ? map[0].length : starty + maxYTiles;
	batch.disableBlending();
	batch.begin();
	for (int i = startx; i < maxw; i++) {
	    int[] is = map[i];
	    for (int j = starty; j < maxh; j++) {
		int k = is[j];
		k--;
		if (k != -1) {
		    paintTile(batch, i * tileWidth, j * tileHeight, k);
		}
	    }
	}
	batch.end();
	batch.enableBlending();
    }

    protected void paintTile(SpriteBatch batch, int x, int y, int id) {
	batch.draw(tiles[id], x, y);
    }

    public int[][] getMap() {
	return this.map;
    }

    public void setMap(final int[][] map) {
	this.map = map;
    }

    public TextureRegion[] getTiles() {
	return this.tiles;
    }

    public int getTileWidth() {
	return (int) (this.tileWidth * GameContext.SCALING_X);
    }

    public int getTileHeight() {
	return (int) (this.tileHeight * GameContext.SCALING_Y);
    }

    public int getHorizontalTilesNumber() {
	return this.horizontalTilesNumber;
    }

    public int getVerticalTilesNumber() {
	return this.verticalTilesNumber;
    }

    public int getMaxXTiles() {
	return maxXTiles;
    }

    public int getMaxYTiles() {
	return maxYTiles;
    }

    public void scale() {

    }
}
