// Generated by delombok at Sun Dec 01 13:28:22 MSK 2013
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package spaceisnear.game.messages;

import lombok.*;
import spaceisnear.game.objects.*;

/**
 * Sent only by server as a result of Items' interactions.
 *
 * @author White Oak
 */
@NoArgsConstructor(access = AccessLevel.PROTECTED) public class MessageCreated extends Message implements NetworkableMessage {

    @Getter private GameObjectType type;
    @Getter private int id;

    public MessageCreated(GameObjectType type, int id) {
	this(type, MessageType.CREATED_SIMPLIFIED, id);
    }

    protected MessageCreated(GameObjectType type, MessageType type1, int id) {
	super(type1);
	this.type = type;
	this.id = id;
    }

}
