// Generated by delombok at Sun Dec 01 13:28:22 MSK 2013
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package spaceisnear.game.messages.service.onceused;

import lombok.Getter;
import spaceisnear.game.bundles.MessageBundle;
import spaceisnear.game.messages.Message;
import spaceisnear.game.messages.MessageType;
import spaceisnear.game.messages.NetworkableMessage;

/**
 * Sent only when client is connected to server for the first time.
 *
 * @author White Oak
 */
public class MessageClientInformation extends Message implements NetworkableMessage {

    @Getter private final String desiredNickname;

    public MessageClientInformation(String desiredNickname) {
	super(MessageType.CLIENT_INFO);
	this.desiredNickname = desiredNickname;
    }

    @Override
    public MessageBundle getBundle() {
	MessageBundle messageBundle = new MessageBundle(getMessageType());
	messageBundle.bytes = desiredNickname.getBytes();
	return messageBundle;
    }

    public static MessageClientInformation getInstance(byte[] b) {
	return new MessageClientInformation(new String(b));
    }
}
