// Generated by delombok at Sun Dec 01 13:28:22 MSK 2013
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package spaceisnear.game.messages.service.onceused;

import com.google.gson.Gson;
import spaceisnear.game.bundles.Bundle;
import spaceisnear.game.bundles.MessageBundle;
import spaceisnear.game.messages.Message;
import spaceisnear.game.messages.MessageType;
import spaceisnear.game.messages.NetworkableMessage;

public class MessageWorldSent extends Message implements NetworkableMessage {
	private final String world;
	
	public MessageWorldSent(String world) {
		super(MessageType.WORLD_SENT);
		this.world = world;
	}
	
	@Override
	public MessageBundle getBundle() {
		MessageBundle messageBundle = new MessageBundle(getMessageType());
		messageBundle.bytes = new Gson().toJson(this).getBytes();
		return messageBundle;
	}
	
	public static MessageWorldSent getInstance(byte[] b) {
		return new Gson().fromJson(new String(b), MessageWorldSent.class);
	}
	
	
	public String getWorld() {
		return this.world;
	}
}