// Generated by delombok at Sun Dec 01 13:28:22 MSK 2013
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package spaceisnear.game.messages.service.onceused;

import com.google.gson.Gson;
import spaceisnear.game.bundles.MessageBundle;
import spaceisnear.game.messages.Message;
import spaceisnear.game.messages.MessageType;
import spaceisnear.game.messages.NetworkableMessage;

/**
 * Sent only when client is connected to server for the first time.
 *
 * @author White Oak
 */
public class MessageClientInformation extends Message implements NetworkableMessage {
	private final String desiredNickname;
	
	public MessageClientInformation(String desiredNickname) {
		super(MessageType.CLIENT_INFO);
		this.desiredNickname = desiredNickname;
	}
	
	@Override
	public MessageBundle getBundle() {
		MessageBundle messageBundle = new MessageBundle(getMessageType());
		messageBundle.bytes = new Gson().toJson(this).getBytes();
		return messageBundle;
	}
	
	public static MessageClientInformation getInstance(byte[] b) {
		return new Gson().fromJson(new String(b), MessageClientInformation.class);
	}
	
	
	public String getDesiredNickname() {
		return this.desiredNickname;
	}
}